language: python
# command to install dependencies
install:
  - pip install virtualenv python-coveralls
# # command to run tests
script: python setup.py test
after_success:
  - pip install -r requirements-testing.txt -e .
  - py.test --cov=poke_jenkins --cov-report=term-missing tests
  - coveralls
notifications:
    email:
        - opensource-tests@paylogic.com
